source 'https://rubygems.org'


#Default gems

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

#------------------------------------------------------------------------------------------------

#Gems added for SocialDashboard

#Bootstrap.
gem "twitter-bootstrap-rails"
gem "therubyracer"
gem "less-rails"

# Use FontAwesome styles.
gem "font-awesome-rails"

# Use haml instead of erb.
gem "haml-rails"

#Use i18n for internationalization.
gem 'rails-i18n', '~> 4.0.0'

#Use twitter api client
gem 'twitter'

#Use Ruby graph library.
gem 'rgl'

#Use bootstrap datepicker
gem 'momentjs-rails', '>= 2.8.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.0.0'

#To set environment variables
gem "figaro"